### ISSUE TITLE
Do we need a separate npm package for it?

### ISSUE THREAD

**Issue by okonet** [skyharbor/react-dropzone#3]
Hey,

I'm a contributor of `react-dropzone` and just stumbled upon this repository by accident. 

I'm wondering if world needs two libraries (and 2 npm packaged) for the same thing but with different syntax. Would you like to merge it back to original project and deprecate the npm package?

I was intendent to convert it to ES6 sooner or later myself so this would be a help and also less confusion for npm users I think.

**Comment by dnikiel** [comment]
Sure, I will deprecate this npm package.

**Comment by okonet** [comment]
Cool! Thanks for understanding.
